[program:server_qr]
user=USER
command=/home/USER/prod/qrserver/run --socket /run/qrserver/qr.sock
directory=/home/USER/prod/qrserver
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/qrserver.out.log
stderr_logfile=/var/log/supervisor/qrserver.err.log
stopsignal=SIGKILL
stopwaitsecs=3
killasgroup=true
stopasgroup=true
